### ISSUE TITLE
Api available?

### ISSUE THREAD

**Issue by csumrell** [dmihal/l2-fees#5]
Is there any API available for this like for cryptofees? (for example https://cryptofees.info/api/v1/fees)

**Comment by dmihal** [comment]
Hey @csumrell, sorry for the late response

This data can be queried using the CryptoStats API or SDK. You can generate a query on this page https://cryptostats.community/discover/l2-fees, for example https://api.cryptostats.community/api/v1/l2-fees/feeTransferEth?metadata=false

I'm closing this for now, let me know if you have any questions, or feel free to join the CryptoStats Discord
